---
- name: AWS operations
  hosts: localhost
  gather_facts: False
  vars:
    region: ap-south-1
    ami: ami-04ea996e7a3e7ad6b
    keypair: demo_jenkins
    instance_type: t2.micro
    security_group: demo
  tasks:
    - name: launch ec2 instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        wait_timeout: 60
        count: 1
        group: "{{ security_group }}"
        vpc_subnet_id: subnet-478d0d2f
        assign_public_ip: yes
        region: "{{ region }}"
      register: ec2

    - name: debugging
      debug: msg="test debugging {{ ec2 }}"
      
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 30
      with_items: "{{ ec2.instances }}"

    - name: attach volume
      ec2_vol:
        instance: "{{ item.id }}"
        volume_size: 5
        region: "{{ region }}"
      with_items: "{{ ec2.instances }} "
      register: ec2_vol_info
    - name: debugging ec2 volume
      debug: var=ec2_vol_info
    - name: volume info
      debug: msg="volume info is {{ ec2_vol_info}}"
